import { NavBar } from '@/components/NavBar';
import './globals.css'
import type { Metadata } from 'next'

import { createClient } from 'pexels';

// const client = createClient(process.env.PIXEL_API_TOKEN as string);
// const query = 'Nature';

// client.photos.search({ query, per_page: 2, page: 10 }).then(photos => {
//   console.log(photos)
// });
export const revalidate = 3600

export const metadata: Metadata = {
  title: 'Next.js Image Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <NavBar />
        <main className='max-w-6xl mx-auto'>
          {children}
        </main>
      </body>
    </html >
  )
}
